### ISSUE TITLE
When running with fix flag, not all files are automatically fixed

### ISSUE THREAD

**Issue by zkwsk** [ota-meshi/eslint-plugin-jsonc#170]
I have a project with lets say 30 JSON files that need to be sorted case sensitive.

I run the command `eslint ./**/*.json --fix`

Then I run it again without the fix flag and learn that it has only fixed 13 out of 30 files:

```
✖ 17 problems (17 errors, 0 warnings)
  17 errors and 0 warnings potentially fixable with the `--fix` option.
```

I repeat the process above and get down to 13 errors, then 10 errors, etc.

Any idea why `eslint --fix` does not fix all my files in one go?

I'm running this inside a Next.js project using the built-in linting settings. In addition I have the following configuration in .eslintrc.js:

```
...
    'jsonc/sort-keys': [
      'error',
      'asc',
      {
        caseSensitive: true,
        natural: false,
        minKeys: 2,
      },
    ],
...
```

Any idea what might be going on?

**Comment by ota-meshi** [comment]
ESLint's auto-fix will auto-fix 10 times within the range where there is no conflict. Perhaps your file needed more auto-fixes.

https://github.com/eslint/eslint/blob/f836743e95cb8ad3bdd4e88687dbe2f16bfade62/lib/linter/linter.js#L1974
https://github.com/eslint/eslint/blob/f836743e95cb8ad3bdd4e88687dbe2f16bfade62/lib/linter/linter.js#L44

Also, the sort rule does not auto-fix all the orders at once. Because it may be ignored by suppressive comments. One problem report auto-fix only that one order. This means that it may require a large number of auto-fixes.

If running once does not solve all the problems, you need to run it multiple times.
